{
 "title": "JWT Pizza",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Pizza Revenue per minute",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizzaRevenue_USD_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizzas Ordered",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(pizzasOrdered_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(failedOrderAttempts_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "rate(totalRequests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\", method=\"PUT\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\", method=\"DELETE\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\", method=\"GET\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\", method=\"POST\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "description": "The number of active users",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "activeUsers_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication Attempts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "rate(authenticationAttempts_total{source=\"jwt-pizza-service\", status=\"failed\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(authenticationAttempts_total{source=\"jwt-pizza-service\", status=\"successful\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Percent of the CPU being used.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "factoryLatency_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "requestLatency_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Percent of the memory being used.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memoryUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}